### ISSUE TITLE
Gate not working

### ISSUE THREAD

**Issue by jamesblackwell** [laravel/pulse#140]
### Pulse Version

dev-card-customisation

### Laravel Version

10.8

### PHP Version

8.2.5

### Description

I've defined the gate exactly as per the docs. However it doesn't seem to be used. 

If I change my environment to production, it's always 403. 

It's odd because I have Nova running with a gate as well and that works but the Gate defined in AuthServiceProvider never seems to be called. 

I tried dd'ing the value of static::$authUsing in Pulse.php and it is always null. 

### Steps To Reproduce

Install pulse, setup as per docs.

**Comment by ahmic** [comment]
Do you have column `name` in `users` table?

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by timacdonald** [comment]
Can you please put a `dd` before you define the gate and ensure that the service provider is actually running.

Can you please copy and paste the gate definition for us to see.

Can you also let us know what method in the service provider you are defining the gate in.

Lastly, it would be good as Mior asked to provide a small demo application showing the problem.

**Comment by timacdonald** [comment]
@jamesblackwell it seems like you might be running an other version of Pulse before we introduced the Gate, as `authUsing` doesn't exist any more.

Please update to the latest beta.
