### ISSUE TITLE
Add notifications feature for pulse:work

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/pulse#203]
Hi, I've just tried using Pulse in production. I'm trying out using the `pulse:work` command in conjunction with Redis, and it's occurred to be that if for whatever reason the `pulse:work` command fails, or doesn't run, maybe because of something wrong with supervisor or another process management utility that my Redis injest will fill up quickly, never clear, and likely crash Redis.

Is it possible to handle this and send some notification if it builds up quickly?

**Comment by timacdonald** [comment]
Hi, @sts-ryan-holton, we have built in things for this.

1. When the `pulse:work` command fails, an exception should be thrown and appear in your error tracker / logs.
2. Whenever we write to the Redis ingest we also trim the ingest so that it does not overflow. That trimming happens on a lottery basis. You can configure the odds the lottery will succeed with the `pulse.ingest.trim_lottery` configuration option.
3. I'm got an open PR that will also allow you to configure the length you want to allow in the ingest when trimming. You may specify a value in time or length, e.g., `"2 days"` which will trim entries in Redis that are older than 2 days or `"500"` which will ensure Redis only contains the latest 500 entries and the others are dropped from the stream. It currently defaults to `"7 days"`.


Hope all this helps. Keep an eye on this one: https://github.com/laravel/pulse/pull/184 to configure the length to trim.
