### ISSUE TITLE
Application usage stops working when horizon is ignored

### ISSUE THREAD

**Issue by AiAe** [laravel/pulse#287]
### Pulse Version

v1.0.0-beta9

### Laravel Version

10.41.0

### PHP Version

8.2.13

### Livewire Version

3.2

### Database Driver & Version

MariaDB 10.5.13

### Description

When I add to pulse's config UserRequests to ignore `#^/horizon` it never will log any site activity again.
Cache and Queue driver use Redis

### Steps To Reproduce

1. Have Pulse and Horizon installed
2. Add horizon to the ignored list in UserRequests`#^/horizon` 
3. It will not longer log any site activity

**Comment by timacdonald** [comment]
@AiAe I have just tested and I can safely ignore the `/horizon` route and things continue to work.

I believe you might have a malformed regex. Make the following change:

```diff
'ignore' => [
-     '#^/horizon',
+     '#^/horizon#',
],
```

This was likely throwing an exception, which is why you no longer saw any data. Pulse swallows all exceptions to ensure that it does not interfere with your application or impact your users.

You may want to setup exception reporting / logging for any exceptions Pulse encounters.

```php
use Laravel\Pulse\Facades\Pulse;
use Illuminate\Support\Facades\Log;
 
Pulse::handleExceptionsUsing(function ($e) {
    Log::debug('An exception happened in Pulse', [
        'message' => $e->getMessage(),
        'stack' => $e->getTraceAsString(),
    ]);
});
```

See: https://laravel.com/docs/10.x/pulse#pulse-exceptions

**Comment by AiAe** [comment]
@timacdonald thanks, this resolved the issue. 
I just noticed that the other examples also end with `#`.
