### ISSUE TITLE
Can "groups" reduce pulse_entries table size

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/pulse#292]
Hi,

I'm working on a Laravel application that processes thousands of events per minute, and there's a lot of cache interactions, hundreds of thousands per day, a lot of them can be grouped, which I've done in the `Recorders\CacheInteractions::class`.

I've grouped some things in `groups`, which is working, but I still see a large amount of data accumulating in the `pulse_entries` table.

Does the `pulse_entries` table reduce record inserts when grouping, or does it still log everything but deleted automatically, trying to figure out how best to reduce the table size beyond sampling?

```php
Recorders\CacheInteractions::class => [
    'enabled' => env('PULSE_CACHE_INTERACTIONS_ENABLED', true),
    'sample_rate' => env('PULSE_CACHE_INTERACTIONS_SAMPLE_RATE', 1),
    'ignore' => [
        ...Pulse::defaultVendorCacheKeys(),
    ],
    'groups' => [
        '/^job-exceptions:.*/' => 'job-exceptions:*',
        '/^health:checks:.*/' => 'health:checks:*',
        '/^laravel-health:check-.*/' => 'laravel-health:check:*',
        '/^dashboard_stats_.*/' => 'dashboard_stats_*',
        '/^archive:db:.*/' => 'archive:db:*',
        '/^setting_company_.*/' => 'setting_company_*',
        '/^rate_limiter_httpapi:.*/' => 'rate_limiter_httpapi:*',
        '/^filters_:.*/' => 'filters_*',
        '/:\d+/' => ':*',
    ],
],
```

**Comment by jessarcher** [comment]
> Does the pulse_entries table reduce record inserts when grouping, or does it still log everything but deleted automatically, trying to figure out how best to reduce the table size beyond sampling?

Grouping only reduces the size of the `pulse_aggregates` table as it reduces the number of unique buckets. See https://github.com/laravel/pulse/issues/293#issuecomment-1911221048 for a more detailed explanation of what the `pulse_entries` table is used for.

Sampling is the only way to reduce the number of rows in `pulse_entries`. The more activity you have, the lower you can set your sample rate without sacrificing too much accuracy. We've allowed the sample rate to be tuned individually for each metric so that applications with a lot of activity in one area and not much in another, can still achieve acceptable accuracy across the board.

Data in `pulse_entries` and `pulse_aggregates` is automatically deleted once it's no longer required. `pulse_entries` records are kept for 7 days (see https://github.com/laravel/pulse/issues/293#issuecomment-1911221048), and `pulse_aggregates` are deleted based on the period. I.e. the 60-second buckets are deleted after an hour, and so on.

**Comment by sts-ryan-holton** [comment]
@jessarcher Is there a way to retain less data in the `pulse_entries` table? You say 7 days, is that configurable?
