### ISSUE TITLE
Can pulse_entries table provide an aggregated count column instead of duplicate rows Cache

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/pulse#293]
Hi :wave:

This is sort of related to my [other question](https://github.com/laravel/pulse/issues/292), but I'm aware that we have sampling and the ability to group things together, but I'd love it if, for example, rather than creating N number of rows in the `pulse_entries` table, just have a `record_count` column, and increment the column for that row if another item comes in matching the same `key_hash` column.

This way, we'd significantly reduce the number of rows built up in the `pulse_entries` table. What are your thoughts?

**Comment by jessarcher** [comment]
Hi @sts-ryan-holton,

The `pulse_aggregates` table already does this and is the primary source of data for the dashboard.

The `pulse_entries` table needs to keep individual rows with their specific dates as it's only used to fill in the gap where a bucket from `pulse_aggregates` falls partially outside the window.

For example, if we take the 1-hour view, then there are buckets in `pulse_aggregates` for each minute for the past hour:

```
09:20:00 - 09:20:59
09:21:00 - 09:21:59
09:22:00 - 09:22:59
...
10:18:00 - 10:18:59
10:19:00 - 10:19:59
10:20:00 - 10:20:59
```

Given the above example, imagine the time is currently 10:20:30. That means we want to query data from 09:20:30 - 10:20:30. We can't include the `09:20:00 - 09:20:59` bucket because it contains data from outside the window, so we use the `pulse_entries` table just to fill in the data from 09:20:30 - 09:20:59 (we call this the "tail") and the remaining data comes from `pulse_aggregates`. The `10:20:00 - 10:20:59` bucket can be included because it's only partially full at that point (i.e. it only contains data from 10:20:00 - 10:20:30).

On the 1-hour view, the tail size can be anywhere from 1 second to 59 seconds, depending on the current time. If we zoom out to the 7-day view, the bucket sizes are 2 hours and 48 minutes each (7 days divided by 60), so the size of the tail can be anywhere from 1 second to 2 hours, 47 minutes, and 59 seconds - depending on the current time. It will always be less than a 60th of the data needed to generate stats for the current period as everything else comes from the pre-aggregated data in `pulse_aggregates`.

If the `pulse_entries` data were collapsed, we couldn't query for the very specific window of the "tail", which changes every second. It can become a very large table, but only a very small portion is ever needed at any given point in time.

I guess records from the same second could be collapsed, but I don't know how worthwhile that would be.

I will be explaining more about how this all works at Laracon EU in just over a week if you happen to be around!

**Comment by sts-ryan-holton** [comment]
@jessarcher Thanks for the comprehensive detailed explanation, it's an interesting thought. In my application, which processes thousands of records (unrelated to Pulse), I have gone with the approach of creating three tables, a `minuely` table, an `hourly` table and a `daily` table. In each table, I provide a `logged_at` datetime column whereby the minutely table aggregates all of the same data by a particular uniqueness for a particular minute, similar approach to the hourly and daily.

The note here, is that I truncate the `minutely` table beyond a day, the `hourly` table beyond a few days, and never/rarely truncate the `daily` table. This way I'm able to provide users with a minute by minute trend, as I am hourly and daily.

The benefit here is that when zooming out to larger periods, I have the option to use the hourly or daily.

Each table is all handled by one event listener, and it effectively uses the `firstOrCreate` method to either create or return the record if it exists, and then uses the `increment` method to increment a column, and this approach has worked quite well on millions of entries.

What are your thoughts on this?
