### ISSUE TITLE
Requires InnoDB in case of a MySQL database

### ISSUE THREAD

**Issue by bobinwood** [laravel/pulse#321]
### Pulse Version

1.0.0.beta13

### Laravel Version

10.45.0

### PHP Version

8.1.21

### Livewire Version

3.4.6

### Database Driver & Version

MySQL 5.7.14

### Description

After installation , when you run run `php artisan migrate ` you got the following error:
 `SQLSTATE[HY000]: General error: 1478 Table storage engine 'MyISAM' does not support the create option 'Index on virtual generated column' (Connection: mysql, SQL: alter table pulse_values add unique pulse_values_type_key_hash_unique(type, key_hash))`

### Steps To Reproduce

You have a database with by default MyIsam as default Engine
`composer require laravel/pulse`
`php artisan vendor:publish --provider="Laravel\Pulse\PulseServiceProvider"`
`php artisan migrate`

**Comment by jbrooksuk** [comment]
Pulse is not compatible with MyISAM as we're specifically using features only available to InnoDB. @jessarcher has previously mentioned that we could look at specifically forcing these migrations to always use InnoDB.

**Comment by timacdonald** [comment]
We recommend adding the following to your project's published migrations within each `Schema::create` call.

```php
$table->engine = 'InnoDB';
```

**Comment by abaldwinls** [comment]
Good afternoon, 
This issue made me look deeper at the migrations for Pulse & I noticed the index on a virtual column. I've done that in the past when working with dates. It worked ok in MySQL 5.7, but in versions of 8, I've had it crash MySQL to the point where it threw a stack trace & corrupted the index. I posted the bug in the MySQL forums, they said it "was an internal bug and being addressed", then was hidden from the public (super weird, but anyway). 

Maybe it was fixed in the past ~year since I reported it, but just thought I'd share the info as it was pretty catastrophic for us. Using "GENERATED ALWAYS AS _____ STORED" resolved the issue & haven't had crashes since then.
