### ISSUE TITLE
Support for sqlsrv

### ISSUE THREAD

**Issue by MiloDBD** [laravel/pulse#328]
It is on the road map to support sqlsrv. I know many would like this.

Thank you

**Comment by jessarcher** [comment]
Hi @MiloDBD,

I'm open to this, but I'm not sure what's involved. There are a few less common database techniques we use in Pulse, namely generated indexed hash columns and upsert queries, which have their own intricacies with each database engine. If you search the code base for `sqlite`, you'll see where each of these database-specific code paths live.

I'll add it to my list to look at, but please feel free to try a PR for it. I'd appreciate any guidance, especially on the most efficient way to store and index the generated hashes. In MySQL, we used a fixed-length binary column, but this doesn't column type doesn't exist on Postgres where it turned out that using a UUID column was a very efficient way to store an MD5 hash.

**Comment by timacdonald** [comment]
And remember you can use a dedicated database for Pulse, so you can use sqlsrv for your application and spin up a dedicated mysql / postgres / sqlite database for Pulse itself.

**Comment by jessarcher** [comment]
I just tried this in #329 to see if it was a quick win, but I couldn't get it to work. I'm going to close this for now, but we're open to PRs if you or anyone else can figure it out :+1:
