### ISSUE TITLE
High Cpu Usage

### ISSUE THREAD

**Issue by srezaFallahi** [laravel/pulse#388]
### Pulse Version

1.2

### Laravel Version

10.48.12

### PHP Version

8.1

### Livewire Version

3.0.2

### Database Driver & Version

MySQL 8.0

### Description

hi 
i install pulse in production it's used CPU core before install pulse my CPU usage did about 4 core but after that it's use 12 core CPU why ? 

### Steps To Reproduce

just put it on heavy load

**Comment by timacdonald** [comment]
@srezaFallahi, please review the Performance section of the Laravel Pulse documentation: https://laravel.com/docs/11.x/pulse#performance

For any applications with significant traffic I would recommend looking at the following improvements, in this order:

1. Using the `redis` ingest instead of the `storage` ingest.
2. Using a dedicated server for Pulse to host both the Redis instance and the database storage instance.
3. Using Sampling to decrease the amount of data the application is trying to capture.
