### ISSUE TITLE
Pulse is ignoring timezone setting

### ISSUE THREAD

**Issue by maciek-szn** [laravel/pulse#410]
### Pulse Version

1.2.5

### Laravel Version

11.25.0

### PHP Version

8.3.10

### Livewire Version

3.5.8

### Description

After updating Laravel to version 11, Pulse stopped honoring the timezone setting. This may be due to updating Carbon to version 3. Data is presented according to UTC time zone, even though the time zone is set to "Europe/Warsaw" (both in Laravel and PHP configuration).

### Steps To Reproduce

Set your Laravel timezone to something other than "UTC" and observe the timeline in your Pulse charts.

**Comment by timacdonald** [comment]
Hi, @maciek-szn, thanks for reporting this. I've just some testing and wanted to confirm what I'm seeing is what you are reporting.

I can see that everything still works as expected. The graphs still show the right data in the right places, e.g., data from "now" is always at the right-hand side.

The problem being that when you hover over the dates is you see UTC time in the browser rather than your own timezone.

You would like to see Warsaw's time in this popup, i.e., 2024-10-02 00:36:00 rather than the same time but in UTC format.

<img width="328" alt="Screenshot 2024-10-02 at 08 37 39" src="https://github.com/user-attachments/assets/0b76831d-9725-430c-9283-9bd7207d668d">

**Comment by timacdonald** [comment]
I feel that we should likely display the time in your browsers timezone, rather than the applications timezone - potentially with UTC alongside.

**Comment by maciek-szn** [comment]
> You would like to see Warsaw's time in this popup, i.e., 2024-10-02 00:36:00 rather than the same time but in UTC format.

Indeed. In Laravel 10 (i.e. Carbon 2) everything works fine. I didn't look into the code, but maybe [that's the reason](https://carbon.nesbot.com/docs/#api-carbon-3-create-from-timestamp-utc).

**Comment by timacdonald** [comment]
Closing this one as we have a PR open for this: https://github.com/laravel/pulse/pull/417
