### ISSUE TITLE
Cannot use object of type InfyOm\Generator\Common\GeneratorConfig as array

### ISSUE THREAD

**Issue by zyood01** [laravel/pulse#416]
### Pulse Version

1.2

### Laravel Version

10.4

### PHP Version

8.2

### Livewire Version

3.5

### Database Driver & Version

mysql

### Description

when i try to access /pulse this error appears 

![image](https://github.com/user-attachments/assets/e615e5fa-264c-4cda-b5e8-0b6913de3252)

update API (post) return error 500 with : 

Spatie\LaravelIgnition\Exceptions\ViewException: Cannot use object of type InfyOm\Generator\Common\GeneratorConfig as array in file /**/**/**/******/vendor/laravel/pulse/resources/views/livewire/cache.blade.php on line 12

### Steps To Reproduce

**

**Comment by crynobone** [comment]
https://github.com/InfyOmLabs/laravel-generator which provide the class reported above is not being used by Laravel Framework or Laravel Pulse. This seem to indicate that your application require the package and somehow cause this error.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by zyood01** [comment]
Thank you for the clarification. I thought this happened because of Pulse. I'll check it.
