### ISSUE TITLE
[Question] Recording all URLs (instead of routes)

### ISSUE THREAD

**Issue by ghost** [laravel/pulse#431]
### Pulse Version

1.2.7

### Laravel Version

10.48.23

### PHP Version

8.2

### Livewire Version

3.5.12

### Description

Dear Team, is it possible to configure the slow requests recorder to capture specific URLs (e.g., /category/electronics) instead of generalized route names (e.g., /category/{slug})? Thanks!

### Steps To Reproduce

N/A

**Comment by timacdonald** [comment]
@salvisb, Pulse's first-party cards will only support routes.

If you need specific URLs, you would need to implement your own custom card. You can look at the internal slow requests card and duplicate its logic updating it to capture  request URLs. Just beware that if you have a lot of requests with differing URLs, the aggregated data could get out of hand in your database. We used routes specifically because it could be grouped together.

For what it is worth, [Laravel Nightwatch](https://nightwatch.laravel.com) will allow you to capture both routes and full request URLs.
